### ISSUE TITLE
Add aliases for ease of assembly

### ISSUE THREAD

**Issue by DJLevel3** [Haku8866/URCL#1]
I'm about to start a project to port Atari Asteroids from 6502 ASM to URCL, but I need to use aliases for memory locations or it'll be unreadable. Here's a snippet of the source assembly (with the locations defined earlier):
```
L684E:  LDA PlyrDispTimer       ;Is player not active?
L6850:  BNE DoAsteroids         ;If not, branch.

L6852:  jsr UpdateShip          ;($6CD7)Update ship firing and position.
L6855:  jsr EnterHyprspc        ;($6E74)Check if player entered hyperspace.
L6858:  jsr ChkExitHprspc       ;($703F)Check if coming out of hyperspace.
L685B:  jsr UpdateScr           ;($6B93)Update saucer status.
```
Apparently there's a function of URCL with the syntax `@DEFINE PlyrDispTimer #5A`, but as far as I know this transpiler doesn't support it.

I'll take a look at the source code and see if I can implement it and PR, but if I can't then can you take a crack at it?

**Comment by Haku8866** [comment]
Yes, `@DEFINE` was added in a newer version of URCL. It seems fairly easy to add, I'll take a look at it now. Thanks for letting me know!
